name: Docker Build and Push

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DEFAULT_VERSION: 0.0.0

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Update version based on commit messages
        run: |
          # Get the commit messages since the last tagged commit
          COMMIT_MESSAGES=$(git log --oneline --format=%B $(git describe --tags --abbrev=0)..HEAD)
          
          # Check if the commit messages contain the keyword "MINOR" or "MAJOR"
          if echo "$COMMIT_MESSAGES" | grep -q "MINOR"; then
            # Increment the minor version
            NEW_VERSION=$(echo "${{ env.DEFAULT_VERSION }}" | awk -F. '{$2++; print $1"."$2"."0}')
          elif echo "$COMMIT_MESSAGES" | grep -q "MAJOR"; then
            # Increment the major version
            NEW_VERSION=$(echo "${{ env.DEFAULT_VERSION }}" | awk -F. '{$1++; $2=0; $3=0; print $1"."$2"."$3}')
          else
            # Increment the patch version (default)
            NEW_VERSION=$(echo "${{ env.DEFAULT_VERSION }}" | awk -F. '{$3++; print $1"."$2"."$3}')
          fi
          
          # Set the updated version as an output variable
          echo "::set-output name=version::$NEW_VERSION"
        id: update_version

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
          tags: |
            type=raw,value=v${{ steps.update_version.outputs.version }}
            type=raw,value=v${{ steps.update_version.outputs.version }}-{{sha}}

      - name: Build and push Docker image
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}